# Generated by Django 4.2.4 on 2023-08-31 15:34

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id_kat', models.AutoField(primary_key=True, serialize=False)),
                ('tytul_kat', models.CharField(max_length=80)),
                ('opis', tinymce.models.HTMLField()),
                ('url', models.SlugField(blank=True, max_length=80, unique=True)),
                ('obraz', models.ImageField(upload_to='kategoria/')),
                ('kiedy_dodane', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('tytul_post', models.CharField(max_length=80)),
                ('tekst', tinymce.models.HTMLField()),
                ('url', models.SlugField(blank=True, max_length=80, unique=True)),
                ('obraz', models.ImageField(upload_to='posty/')),
                ('kiedy_dodane', models.DateTimeField(auto_now_add=True, null=True)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('id_komment', models.AutoField(primary_key=True, serialize=False)),
                ('tekst', tinymce.models.HTMLField()),
                ('kiedy_dodane', models.DateTimeField(auto_now_add=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Komentarze', to='core.post')),
            ],
        ),
    ]
